export const NAV_CONFIG = {
  SCROLL_SMOOTH_BEHAVIOR: 'smooth' as const,
  SCROLL_PADDING_TOP: 80,
  SCROLL_THRESHOLD: 100,
}

export const ANIMATION_CONFIG = {
  SCROLL_HINT_DURATION: 2,
  SCROLL_HINT_DELAY: 0.5,
  SCROLL_REVEAL_THRESHOLD: 0.1,
  SCROLL_REVEAL_MARGIN: '0px 0px -100px 0px',
  TYPEWRITER_SPEED: 100,
  TYPEWRITER_DELETE_SPEED: 50,
  TYPEWRITER_PAUSE: 2000,
}

export const SCROLL_CONFIG = {
  SCROLL_THRESHOLD: 300,
  SCROLL_BEHAVIOR: 'smooth' as const,
  OBSERVER_ROOT_MARGIN: '-50% 0px -50% 0px',
  OBSERVER_THRESHOLD: [0, 0.5, 1],
  SCROLL_EVENT_THROTTLE: 150,
}

export const PERFORMANCE_CONFIG = {
  ENABLE_LAZY_LOADING: true,
  ENABLE_LOADING_SCREEN: true,
  LAZY_LOAD_DELAY: 300,
}
